import ShortUniqueId from "short-uuid";

const translator = ShortUniqueId();

/**
 * Generates a new unique card ID using short-uuid
 * @returns A short UUID string (e.g., "mhvXdrZT4jP5T8vBxuvm75")
 */
export function generateCardId(): string {
    return translator.new();
}

/**
 * Validates that a string is a valid card ID format
 * Card IDs are short UUIDs generated by short-uuid library
 * @param cardId The card ID to validate
 * @returns true if the card ID is valid, false otherwise
 */
export function validateCardId(cardId: string): boolean {
    if (!cardId || typeof cardId !== "string") {
        return false;
    }
    // short-uuid generates IDs that are alphanumeric with hyphens and underscores
    // Typical format: 22 characters, alphanumeric
    // We'll validate it's a reasonable length and contains valid characters
    const cardIdRegex = /^[a-zA-Z0-9_-]{20,30}$/;
    return cardIdRegex.test(cardId);
}
